/*
 * strategie.c
 *
 * "test"
 *
 * Generated by Ares ENSEA Simulator.
 * https://ares.asso-ensea.fr/simulateur/
 * 
 * Created at 23:32 on 11/07/2021.
 */

#include <strategie.h>

int nb_points = 7;

CONSIGNE consigneBleu[7] = {
    {
      .x = 0, .y = 0, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 550, .y = 0, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 550, .y = -300, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
//      .x = 350, .y = -300, .dir = FORWARD,
//      .pinces = { FALSE, FALSE, FALSE, FALSE },
//      .bras = FALSE
//    }, {
//      .x = 550, .y = -300, .dir = FORWARD,
//      .pinces = { FALSE, FALSE, FALSE, FALSE },
//      .bras = FALSE
//    }, {
      .x = 550, .y = 0, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 0, .y = 0, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};

CONSIGNE consigneJaune[7] = {
    {
      .x = 2740, .y = 1338, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1685, .y = 1338, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 1685, .y = 559, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2154, .y = 559, .dir = BACKWARD, 
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1685, .y = 559, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1685, .y = 1338, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2740, .y = 1338, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};
