/*
 * strategie.c
 *
 * "test"
 *
 * Generated by Ares ENSEA Simulator.
 * https://ares.asso-ensea.fr/simulateur/
 * 
 * Created at 14:29 on 13/09/2021.
 */

#include <strategie.h>

int nb_points = 7;

CONSIGNE consigneBleu[7] = {
    {
      .x = 260, .y = 1338, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1315, .y = 1338, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 1315, .y = 559, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 846, .y = 559, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1315, .y = 559, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1315, .y = 1338, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 260, .y = 1338, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};

CONSIGNE consigneJaune[7] = {
    {
      .x = 2740, .y = 1338, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1685, .y = 1338, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 1685, .y = 559, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2154, .y = 559, .dir = BACKWARD, 
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1685, .y = 559, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1685, .y = 1338, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2740, .y = 1338, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};
